# Generated by Django 2.0.4 on 2018-11-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('sexo', models.IntegerField(choices=[(0, 'Feminino'), (1, 'Masculino')], default=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo_musical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banda', to='music.EstiloMusical'),
        ),
        migrations.AddField(
            model_name='banda',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banda', to='music.Musico'),
        ),
    ]
