# Generated by Django 2.0.4 on 2018-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='estilo_musical',
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo_musical',
            field=models.ManyToManyField(related_name='banda', to='music.EstiloMusical'),
        ),
    ]
