# Generated by Django 2.0.7 on 2018-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181106_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='estilo_musical',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='musico',
        ),
        migrations.AddField(
            model_name='banda',
            name='musico',
            field=models.ManyToManyField(related_name='banda', to='music.Musico'),
        ),
    ]
