# Generated by Django 2.0.7 on 2018-11-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181111_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='estilo_musical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banda', to='music.EstiloMusical'),
        ),
    ]
